# Generated by Django 4.2.8 on 2024-01-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_alter_flight_destination_alter_flight_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
